[package]
name = "lubot-tomurcuk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true  # yayinlanmaz: kagit uzerinde de boyle
license-file.workspace = true

[dependencies]
lubot-anlama = { path = "../anlama", version = "0.1.0" }

[lints]
workspace = true
